namespace FSharpKeywordTranslator;

public class KeywordsObj
{
    public string Abstract { get; set; }
    public string And { get; set; }
    public string As { get; set; }
    public string Assert { get; set; }
    public string Base { get; set; }
    public string Begin { get; set; }
    public string Class { get; set; }
    public string Const { get; set; }
    public string Default { get; set; }
    public string Delegate { get; set; }
    public string Do { get; set; }
    public string Done { get; set; }
    public string Downcast { get; set; }
    public string Downto { get; set; }
    public string Elif { get; set; }
    public string Else { get; set; }
    public string End { get; set; }
    public string Exception { get; set; }
    public string Extern { get; set; }
    public string False { get; set; }
    public string Finally { get; set; }
    public string Fixed { get; set; }
    public string For { get; set; }
    public string Fun { get; set; }
    public string Function { get; set; }
    public string Global { get; set; }
    public string If { get; set; }
    public string In { get; set; }
    public string Inherit { get; set; }
    public string Inline { get; set; }
    public string Interface { get; set; }
    public string Internal { get; set; }
    public string Lazy { get; set; }
    public string Let { get; set; }
    public string Match { get; set; }
    public string Member { get; set; }
    public string Mod { get; set; }
    public string Module { get; set; }
    public string Mutable { get; set; }
    public string Namespace { get; set; }
    public string New { get; set; }
    public string Null { get; set; }
    public string Of { get; set; }
    public string Open { get; set; }
    public string Or { get; set; }
    public string Override { get; set; }
    public string Private { get; set; }
    public string Public { get; set; }
    public string Rec { get; set; }
    public string Return { get; set; }
    public string Static { get; set; }
    public string Sig { get; set; }
    public string Struct { get; set; }
    public string Then { get; set; }
    public string To { get; set; }
    public string Try { get; set; }
    public string True { get; set; }
    public string Type { get; set; }
    public string Upcast { get; set; }
    public string Use { get; set; }
    public string Val { get; set; }
    public string Void { get; set; }
    public string When { get; set; }
    public string While { get; set; }
    public string With { get; set; }
    public string Yield { get; set; }
}